# Config file for automatic testing at travis-ci.com

language: python
dist: bionic
python:
    - 3.8
    - 3.7

# Install dependencies
before_install:
    - python -m pip install codecov
install:
    - python -m pip install -r requirements.txt
    - python -m pip install .[dev]

# Run testing and static typing
jobs:
    include:
        - stage: typing
          name: "MyPy Static Typing"
          script: mypy nbaspa
        - stage: tests
          name: "Unit tests"
          script: pytest
stages:
    - typing
    - tests
after_success:
    - codecov
