# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8

# Install dependencies
install:
    - pip install -r requirements.txt
    - pip install .[tests]

# Run tests
script: pytest tests
